BOARD_TAG = nano
BOARD_SUB = atmega328old
MONITOR_PORT = /dev/cu.usbserial-1410
ARDUINO_DIR = /Applications/Arduino.app/Contents/Java
USER_LIB_PATH += $(HOME)/Code/arduino-sketches/libraries
ARDUINO_LIBS = SPI Wire Adafruit_GFX_Library Adafruit_SSD1306 RF24

include /usr/local/opt/arduino-mk/Arduino.mk
