BOARD_TAG   = nano
BOARD_SUB   = atmega328
MONITOR_PORT = /dev/tty.wchusbserial1430
ARDUINO_DIR = /Applications/Arduino.app/Contents/Java
ARDUINO_SKETCHBOOK = $(HOME)/code/arduino-sketches
ARDUINO_LIBS = MFRC522 SPI Wire Adafruit_GFX_Library Adafruit_SSD1306

include /usr/local/opt/arduino-mk/Arduino.mk
